apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: weather-store-batch
spec: 
  schedule: "*/5 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: weather-store-batch
              image: ${ECR_HOST}/weather-services/weather-store:0.0.1
              imagePullPolicy: Always
              command: ["python"]
              args:
                - bin/batch_script.py
              env:
                - name: DB_URL
                  valueFrom:
                    secretKeyRef:
                      key: db-url
                      name: db-config
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: db-username
                      name: db-config
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: db-password
                      name: db-config
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      key: db-name
                      name: db-config
                - name: WEATHER_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: api-key
                      name: weather-api-secret
          nodeSelector:
            nodegroup: private-nodegroup
          restartPolicy: OnFailure
            
